name: Update Stock Feed

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes (GitHub minimum)
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run generator
        run: python generate_feed.py

      - name: Commit feed.xml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          git commit -m "Auto-update feed.xml" || echo "No changes to commit"
          git push
